language: ruby
rvm:
  - 2.1.3

# This is just the DangerTest API user token,
# it only has scope to see public repos.
env:
  - DANGER_API_TOKEN=6b4ccd061e3c7b521cf61c11cd1533cfbf91e155

before_install:
  - gem update --system
  - gem install bundler
  - bundle install
  - rake install

script:
  - danger
